### ISSUE TITLE
May have mistakenly write "HW" as "HM"

### ISSUE THREAD

**Issue by wzqvip** [i-TechX/i-TechX.github.io#1]
First of all I really appreciate this project and your hard work. But there are a few mistakes .

No HM(x)
CS132.01_Fall_2021/Homework Solution 作业答案/CS132_HM1_Solution.pdf
Maybe you have mistakenly write "HW" as "HM"

**Comment by why-in-Shanghaitech** [comment]
Thank you for your suggestion! The file name mostly comes from the original course sharing. Now that you've pointed it out, we'll fix it as soon as possible.
